# Generated by Django 3.1.14 on 2022-04-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20220423_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.pokemon'),
        ),
    ]
